openapi: 3.0.3
info:
  title: Product Video service
  description: Microservice Handling database
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
  - Description:  Development server
paths:

  /products:

    post:
      summary: Create a product
      requestBody:
        description: product  to create
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/product'
      responses:
        409:
          description: product already exists
        201:
          description: Product created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Product'

    get:
      summary: Read all product
      responses:
        200:
          description: Returned list of product
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product'

    delete:
      summary: Delete all products
      responses:
        200:
          description: All products are deleted


  /videos/{hash}:
    parameters:
      - name: hash
        in: path
        description: Hash of the product
        required: true
        schema:
          type: string
          example: dQw4w9WgXcQ
        style: simple

    get:
      summary: Read a product
      responses:
        404:
          description: Video not found
        200:
          description: Returned video
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/video'

    put:
      summary: Update a video
      requestBody:
        description: New values of the video
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/video'
      responses:
        400:
          description: Non matching video hashes
        404:
          description: Video not found
        200:
          description: Updated video, returned old values
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/video'

    delete:
      summary: Delete a video
      responses:
        404:
          description: Video not found
        200:
          description: Deleted video

components:
  schemas:
    video:
      type: object
      properties:
        hash:
          type: string
        name:
          type: string
        author:
          type: string
        creationYear:
          type: integer
        duration:
          type: integer
          description: in seconds
        url:
          type: string
      example:
        hash: dQw4w9WgXcQ
        name: Cutest kitty ever
        author: Cat4Life
        creationYear: 2009
        duration: 212
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ

  
