###create a product
POST localhost:8080/produit
Content-Type: application/json

{
  "id": 5,
  "name": "test5",
  "category": "ca5",
  "price": 4
}


### Read all
GET http://localhost:8080/produit


### Read one
GET http://localhost:8080/produit/test


### Update one
PUT http://localhost:8080/produit/test4
Content-Type: application/json

{
  "id": 6,
  "name": "test4",
  "category": "kiki",
  "price": 8
}


### Delete all
DELETE http://localhost:8080/produits

### Delete one
DELETE http://localhost:8080/produits/test